services:
  - type: web
    name: querymind-backend
    runtime: python
    plan: free
    region: oregon
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: TARGET_DATABASE_URL
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: "3.11.11"

  - type: web
    name: querymind-frontend
    runtime: python
    plan: free
    region: oregon
    rootDir: frontend
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run streamlit_app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: BACKEND_URL
        value: "https://querymind-backend-19wq.onrender.com"
      - key: PYTHON_VERSION
        value: "3.11.11"
